### PR TITLE
Added DEPLOY_TAG env to bm-inventory and ui deployment

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Comment by filanov** [comment]
How will it work with the other parameters like `SERVICE`?

**Comment by eranco74** [comment]
I don't know, I'll check.
In theory you should use one of the options but I guess user might want to deploy a specific tag for all images and override one of them (ui / inventory etc).
Checking...

**Comment by filanov** [comment]
Maybe there are other environment variables that can collide? @tsorya ?

**Comment by eranco74** [comment]
Seems that deploy_tag override everything else:
I ran:
```
make run DEPLOY_TAG=v1.0.0 INSTALLER_IMAGE=quay.io/ocpmetal/assisted-installer:latest
```
this is the bm-inventory configmap:
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  AGENT_DOCKER_IMAGE: quay.io/ocpmetal/agent:v1.0.0
  CONNECTIVITY_CHECK_IMAGE: quay.io/ocpmetal/connectivity_check:v1.0.0
  HARDWARE_INFO_IMAGE: quay.io/ocpmetal/hardware_info:v1.0.0
  HW_VALIDATOR_MIN_CPU_CORES: "2"
  HW_VALIDATOR_MIN_CPU_CORES_MASTER: "4"
  HW_VALIDATOR_MIN_CPU_CORES_WORKER: "2"
  HW_VALIDATOR_MIN_DISK_SIZE_GIB: "10"
  HW_VALIDATOR_MIN_RAM_GIB: "3"
  HW_VALIDATOR_MIN_RAM_GIB_MASTER: "8"
  HW_VALIDATOR_MIN_RAM_GIB_WORKER: "3"
  IMAGE_BUILDER: quay.io/ocpmetal/installer-image-build:v1.0.0
  INSTALLER_IMAGE: quay.io/ocpmetal/assisted-installer:v1.0.0
  INVENTORY_IMAGE: quay.io/ocpmetal/inventory:v1.0.0
  INVENTORY_PORT: "6000"
  INVENTORY_URL: 10.19.176.63
  KUBECONFIG_GENERATE_IMAGE: quay.io/ocpmetal/ignition-manifests-and-kubeconfig-generate:v1.0.0
  NAMESPACE: assisted-installer
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"AGENT_DOCKER_IMAGE":"quay.io/ocpmetal/agent:v1.0.0","CONNECTIVITY_CHECK_IMAGE":"quay.io/ocpmetal/connectivity_check:v1.0.0","HARDWARE_INFO_IMAGE":"quay.io/ocpmetal/hardware_info:v1.0.0","HW_VALIDATOR_MIN_CPU_CORES":"2","HW_VALIDATOR_MIN_CPU_CORES_MASTER":"4","HW_VALIDATOR_MIN_CPU_CORES_WORKER":"2","HW_VALIDATOR_MIN_DISK_SIZE_GIB":"10","HW_VALIDATOR_MIN_RAM_GIB":"3","HW_VALIDATOR_MIN_RAM_GIB_MASTER":"8","HW_VALIDATOR_MIN_RAM_GIB_WORKER":"3","IMAGE_BUILDER":"quay.io/ocpmetal/installer-image-build:v1.0.0","INSTALLER_IMAGE":"quay.io/ocpmetal/assisted-installer:v1.0.0","INVENTORY_IMAGE":"quay.io/ocpmetal/inventory:v1.0.0","INVENTORY_PORT":"6000","INVENTORY_URL":"10.19.176.63","KUBECONFIG_GENERATE_IMAGE":"quay.io/ocpmetal/ignition-manifests-and-kubeconfig-generate:v1.0.0","NAMESPACE":"assisted-installer"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"bm-inventory"},"name":"bm-inventory-config","namespace":"assisted-installer"}}

```

**Comment by filanov** [comment]
Need to document it and don't set the DEPLOY_TAG by default right?

**Comment by eranco74** [comment]
> Need to document it and don't set the DEPLOY_TAG by default right?

Done

**Pull request merged**
